### ISSUE TITLE
Doesn't work with ActionPack 4.2.0

### ISSUE THREAD

**Issue by pyro2927** [pmq20/grape-rails-routes#2]
Set this up on a new project using Rails 4.2.0, and when running `rake routes_with_grape` it fails with

```
undefined method `ast' for "/api/game/:slug":String
```

It looks like `ActionDispatch::Journey::Path::Pattern.new` is looking for an expression of some kind.  I will see if I can dig into this to get it working.

**Comment by donbobka** [comment]
:+1:

**Comment by wst07261144** [comment]
我也遇到这个问题了，怎么样解决的，急求解！！

**Comment by datanatas** [comment]
Same problem here.

**Comment by lawzlo** [comment]
same problem.

**Comment by ghost** [comment]
Any progress on this?

**Comment by ikirifqi** [comment]
same problem here

**Comment by dongli** [comment]
I meet this error too. You may find a home-brewed Rake task in [here](https://gist.github.com/oivoodoo/5089237). I put it in my `Rakefile`, and can see the routes by `rake grape:routes`. Thank those guys!

**Comment by yhunglee** [comment]
I got same problem too. Maybe it will be solved by author of the gem accepting the pull request.

**Comment by rosscdh** [comment]
+1
